project:
  type: website
  output-dir: _site
  pre-render:
    - "cp -r ../_extensions ."
    - "./use-dev-binary.sh"
  post-render:
    - "rm -rf _extensions"

extensions:
  term:
    shell: zsh
    init:
      - zsh-syntax-highlighting
      - "setopt INTERACTIVE_COMMENTS"
    spacing: true
    style:
      html:
        colorscheme-light: solarized-dark
        colorscheme-dark: solarized-light

website:
  title: "quarto-term"
  repo-url: https://github.com/jeroenjanssens/quarto-term
  repo-actions: [issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: get-started.qmd
        text: Get Started
      - href: reference.qmd
        text: Reference
      - href: styling.qmd
        text: Styling
      - href: examples.qmd
        text: Examples
      - text: Shells
        menu:
          - href: shells/index.qmd
            text: Overview
          - href: shells/zsh.qmd
            text: Zsh
          - href: shells/bash.qmd
            text: Bash
          - href: shells/fish.qmd
            text: Fish
          - href: shells/nushell.qmd
            text: Nushell
          - href: shells/sh.qmd
            text: POSIX sh
          - href: shells/python.qmd
            text: Python
          - href: shells/node.qmd
            text: Node.js
          - href: shells/ruby.qmd
            text: Ruby
          - href: shells/r.qmd
            text: R
          - href: shells/sqlite.qmd
            text: SQLite
          - href: shells/duckdb.qmd
            text: DuckDB
      - href: docker.qmd
        text: Docker
      - href: demo-formats.qmd
        text: Formats
    right:
      - icon: github
        href: https://github.com/jeroenjanssens/quarto-term

filters:
  - term

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc-depth: 3
    css: styles.css
